version: 2.1
jobs:
  build:
    docker:
      - image: cimg/rust:1.50
        environment:
          DEBUG_BUILD: true
          DEBIAN_FRONTEND: noninteractive

    working_directory: ~/bulletproof-gadgets

    steps:
      - run: ~/bulletproof-gadgets/scripts/init.sh
      - run: ~/bulletproof-gadgets/scripts/test.sh
      - run: ~/bulletproof-gadgets/scripts/build.sh
