// These constants were taken from https://github.com/iden3/circomlib/blob/master/circuits/poseidon_constants.circom
#[cfg(feature = "poseidon_x3_2")]
pub mod x3_2;
#[cfg(feature = "poseidon_x3_3")]
pub mod x3_3;
#[cfg(feature = "poseidon_x3_4")]
pub mod x3_4;
#[cfg(feature = "poseidon_x3_5")]
pub mod x3_5;
#[cfg(feature = "poseidon_x3_6")]
pub mod x3_6;
#[cfg(feature = "poseidon_x3_7")]
pub mod x3_7;
#[cfg(feature = "poseidon_x3_8")]
pub mod x3_8;
#[cfg(feature = "poseidon_x3_9")]
pub mod x3_9;

#[cfg(feature = "poseidon_x5_2")]
pub mod x5_2;
#[cfg(feature = "poseidon_x5_3")]
pub mod x5_3;
#[cfg(feature = "poseidon_x5_4")]
pub mod x5_4;
#[cfg(feature = "poseidon_x5_5")]
pub mod x5_5;
#[cfg(feature = "poseidon_x5_6")]
pub mod x5_6;
#[cfg(feature = "poseidon_x5_7")]
pub mod x5_7;
#[cfg(feature = "poseidon_x5_8")]
pub mod x5_8;
#[cfg(feature = "poseidon_x5_9")]
pub mod x5_9;

#[cfg(feature = "poseidon_x17_2")]
pub mod x17_2;
#[cfg(feature = "poseidon_x17_3")]
pub mod x17_3;
#[cfg(feature = "poseidon_x17_4")]
pub mod x17_4;
#[cfg(feature = "poseidon_x17_5")]
pub mod x17_5;
#[cfg(feature = "poseidon_x17_6")]
pub mod x17_6;
#[cfg(feature = "poseidon_x17_7")]
pub mod x17_7;
#[cfg(feature = "poseidon_x17_8")]
pub mod x17_8;
#[cfg(feature = "poseidon_x17_9")]
pub mod x17_9;

#[cfg(feature = "poseidon_inverse_2")]
pub mod inverse_2;
#[cfg(feature = "poseidon_inverse_3")]
pub mod inverse_3;
#[cfg(feature = "poseidon_inverse_4")]
pub mod inverse_4;
#[cfg(feature = "poseidon_inverse_5")]
pub mod inverse_5;
#[cfg(feature = "poseidon_inverse_6")]
pub mod inverse_6;
#[cfg(feature = "poseidon_inverse_7")]
pub mod inverse_7;
#[cfg(feature = "poseidon_inverse_8")]
pub mod inverse_8;
#[cfg(feature = "poseidon_inverse_9")]
pub mod inverse_9;

pub mod params;
